### ISSUE TITLE
Get data from medium

### ISSUE THREAD

**Issue by Bouncey** [Bouncey/freeCodeCamp-Elasticsearch#2]
Medium rate limits are harsh, I would welcome better ideas 

@evaristoc

**Comment by Bouncey** [comment]
The code it here 

https://github.com/Bouncey/freeCodeCamp-Elasticsearch/blob/master/init/medium/index.js

**Comment by evaristoc** [comment]
@Bouncey:

Not sure about the problem you are having. I haven't tested your code. Is the code you posted a problem or a solution?

If a problem, I don't know if you have tried the following?

I would just make a list of the dates and try the dates instead of trying to parse them automatically.

Make an array of all possible dates and iterate along that array to append the dates in all links like the following:
>https://medium.freecodecamp.com/sitemap/posts/**2016**/posts-**2016-04-28**.xml

Then, divide your project by hours or days accordingly.

The problem will be there will be more errors though: some dates don't have articles and therefore they will take you to nothing.

How long is medium allowing you to continue accessing their lists?

**Comment by Bouncey** [comment]
I am parsing the sitemap to get dates and filtering for articles.

I get pretty far but always hit some limit

**Comment by evaristoc** [comment]
@Bouncey the problem is that I don't really understand were the problem is: Where do you hit the limit? Extracting the info from the map? If so, where it stop? I would say to retry from where it is stopping every time instead. Or do you have to visit the whole xml in order to get the desired page?

I saw your code and it appears that your script look to get all the data in one go. Is it a way to "paginate" the map so you can go directly to the section of the script you want? Or it is that you have to download all the map in order to visit it and that the limit is over how much of the complete map you can download?

If the case is that you have to download the complete map, then we are in trouble. But for what I saw that was not the case.

Going through your code https://github.com/freeCodeCamp/search/blob/master/init/medium/index.js, 

If the problem is at **getting the main xml map**, I would try to include a reference t dates between the beginning and the end of the period:
```
reference_dates = new Reference(<dates>).
```
It seems though that you already did this by calling the map completely in your first step:
```
Observable.fromPromise(extractText(topLevel))
```
Can you verify if the main map is loading completely? If so, this is not the problem.

If it is **the map posts xml the issue**, think about creating some dates hard-coded? Or implement a condition in your code to start downloading data from a certain past date, to see how it behaves?
so in your :
```
.flatMap(postsUrl => 
```
A `if` condition could limit the beginning of `Observable.fromPromise(extractText(postsUrl))`.

If the xml maps are not the problem but **the scraping over the articles**, then I would also suggest to control how far you have got in terms of dates, so you can start the following day from that point. I don't see any "finish" control in your code? For example: any control of response status or error handling could be also useful.

Other thing that might work could be to load the article into the database as soon as it is found - but check it is found!!!. I see the following code instead:
```
flatMap(text => Observable.of({
              title,
              url: postUrl,
              content: text,
              id: hash(postUrl)
            })
```
Followed by a `bulkInsert(...)`. It seems that you are expecting to collect all data before flushing into database.

If you have already a database, I would propose to make an insert where you have a flatMap(...), as well as to add the date of the article: `date: reference_dates[date]`; or at least save that date in a separate file so you know where it stopped. Saving each record instead of all records might slow down the data processing because it has to include smaller async tasks (loading into database) but I think you will have some data already saved by the time it fails. You have to be aware though about the risk of duplication, so you need also to include a step in your code verifying that the record is already in the database.

I am afraid I don't have code to show you. I remember I recommended you the use of the map index, but I haven't explored that approach myself, my approach was very simple and exploratory.

Let me know if this helps?
